language: node_js
node_js:
  - 0.8
env:
  global:
    secure: "IwP4h8ySKru2oxF9bEHGYxyigOcfSZq3eXm4JrdQwW9UHAwb/8X1j5sivJT+\nQvAj8VsbqtPG4oktrlfoy4cMWD4MflzZ/PnDH7wHepuD6QhQcFtg+6o46i7+\nKd7it0qreHDR9KM1w1AxFWqR+e3qsnQFcBBtAMNF+rIByKNSXo0="
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/install_selenium"
  - "sleep 5"
  - "./node_modules/.bin/start_selenium > /dev/null 2>&1 &"
script:
  - "make test_unit"
  - "make test_saucelabs"
  - "sleep 10"
  - "make test_local"
after_script:
  - "./node_modules/.bin/kill_selenium"


