language: node_js
node_js:
  - 0.8
env:
  global:
    secure: "IenGXqu6UcZD5/6N/0HEvI53Tfm0WvC/f+e9AQp/4ZuHUz3jmbSHskOESWzl\n+AhorFff7kgHi72anqPq7sFZ4BVmgTtwJs0hXfnvRAPdzQL1yXQANnc/5mhR\nhiSWPkBp+SPiAvXNwIbzSDTnPX0vt6o0sJFKa56rXdhNsVySR7I="
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/install_selenium"
  - "sleep 5"
  - "./node_modules/.bin/start_selenium > /dev/null 2>&1 &"
script:
  - "make test_unit"
  - "make test_saucelabs"
  - "sleep 10"
  - "make test_local"
after_script:
  - "./node_modules/.bin/kill_selenium"


