language: node_js
node_js:
  - 0.8
env:
  - [
      {secure: "WGuKCvCfr6Q6MNmgd0tvc/lRqUER1o2ibd7Vd6V5EMP0etmNL5djOC2d6iCP\nvTI6U/6R/vK2iuhrNne0MuWEl8AfXlT3mNapo+AMpBibaE9fp5ryaTLqevMS\nzLt1Nmp3NLZ1k6+REW37efUHxJieCk3rsUagJI64d4KSdOvrqWk="},
      {secure: "BaKOBk/AIegTkF/vUcTyPs/5Jh4ccTXZkbUxXw/ihvMC2GexuYh9kR785Ah3\nnNt7LbH4VwNlrnwz347JuF9BIhoXdqIKahr4Inw4hncpgKTA1CmBNZa5ntnG\n3TVzb/L4hXHbHSJWGtiSgRvPQQQM8rj4S4XnJwGeijcqyvCwQy0="}
    ]
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/install_selenium"
  - "sleep 5"
  - "./node_modules/.bin/start_selenium > /dev/null 2>&1 &"
script:
  - "make test_unit"
  - "make test_saucelabs"
  - "sleep 10"
  - "make test_local"
after_script:
  - "./node_modules/.bin/kill_selenium"


