language: node_js
node_js:
  - 0.8
env:
  global:
    secure: "mbQ93JSbGACsOb20Wh/j5i7vA96EPSEYEc+KTaXerQFKmuz24xWOwj5KmNGK\nssMjDtUS2HPY37iyeByNimzyyOUSlj4CzwhBedJ4VfkNMriM7ir5ThyPSidA\neF4BaJUf4Dz50Z6w0ASussSEmeydoEhzbphd8N78wT1HMsLbnRw="
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/install_selenium"
  - "sleep 5"
  - "./node_modules/.bin/start_selenium > /dev/null 2>&1 &"
script:
  - "make test_unit"
  - "make test_saucelabs"
  - "sleep 10"
  - "make test_local"
after_script:
  - "./node_modules/.bin/kill_selenium"


