language: node_js
node_js:
  - 0.8
env:
  - [
      {secure: "F+dTe/x5eB+zSDQPedoVfvFkbD3x4g2mjOho5ztfuV7H2YaLQvrnyyoEBZJq\nWnqB/nxj2nLkLOZWoEHeGMP2eo1X5N8FXbzw4RNpBJOlcuLllofEwmDaGY9x\nogtHIoAb4NixAB+eR9E7ha/Gx8phlabHL0W+VzWMjq/8uDsGIAU="},
      {secure: "p6TeXpeP9NQlekPmwlBst/+HTmgaHahiMbbKV+4iubV5+vfPxc/ye9CVu/JI\n6nbmAlkquOcoyxL8hlZSNo6U4UOTF0DT0AStWUqyIeC27zKKPhv5DUiEs46U\nBDiORjacAyGlEOt2ppV90KRoEiPxDiUMqJD7N6FwcD7t3HsaAow="}
    ]
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/install_selenium"
  - "sleep 5"
  - "./node_modules/.bin/start_selenium > /dev/null 2>&1 &"
script:
  - "make test_unit"
  - "make test_saucelabs"
  - "sleep 10"
  - "make test_local"
after_script:
  - "./node_modules/.bin/kill_selenium"


